"""Symmetric encryption for sensitive config values at rest."""

from __future__ import annotations

from pathlib import Path

from cryptography.fernet import Fernet, InvalidToken

_KEY_FILE = ".key"
_KEY_PERMS = 0o600


def get_or_create_key(config_dir: Path) -> bytes:
    """Return Fernet key bytes, generating and persisting one if absent."""
    path = config_dir / _KEY_FILE
    if path.exists():
        return path.read_bytes().strip()
    key = Fernet.generate_key()
    config_dir.mkdir(parents=True, exist_ok=True)
    path.write_bytes(key)
    path.chmod(_KEY_PERMS)
    return key


def encrypt(value: str, key: bytes) -> str:
    """Encrypt plaintext to a Fernet token string."""
    if not value:
        return value
    return Fernet(key).encrypt(value.encode("utf-8")).decode("ascii")


def decrypt(value: str, key: bytes) -> str:
    """Decrypt a Fernet token string to plaintext.

    Returns the original value unchanged if decryption fails, which handles
    legacy plaintext values and keys generated by other means.
    """
    if not value:
        return value
    try:
        return Fernet(key).decrypt(value.encode("ascii")).decode("utf-8")
    except (InvalidToken, UnicodeError, ValueError):
        return value
